config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  get '/kittens/:id', to: 'kittens#show'
  root to: 'kittens#index'
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  # Kitten Attrubutes from migration
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: %i[ show edit update destroy ]

  # GET /kittens or /kittens.json
  def index
    @kittens = Kitten.all.order("created_at DESC")
    @kitten = Kitten.new
  end

  # GET /kittens/1 or /kittens/1.json
  def show
  end

  # GET /kittens/new
  def new
    @kitten = Kitten.new
  end

  # GET /kittens/1/edit
  def edit
    @kitten = Kitten.find(params[:id])
  end

  # POST /kittens or /kittens.json
  def create
    @kitten = Kitten.new(kitten_params)

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to root_path, notice: "Kitten was successfully created." }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Kitten was failed." }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kittens/1 or /kittens/1.json
  def update
    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to @kitten, notice: "Kitten was successfully updated." }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit, status: :unprocessable_entity, notice: "Kitten was failed." }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kittens/1 or /kittens/1.json
  def destroy
    @kitten.destroy

    respond_to do |format|
      format.html { redirect_to kittens_url, notice: "Kitten was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= simple_form_for(@kitten) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Your kitten's name?" %>
    <%= f.input :age, collection: 0..25, label: "Your kitten's age?" %>
    <%= f.input :cuteness, collection: 1..10, label: "Your kitten's cuteness?" %>
    <%= f.input :softness, collection: 1..10, label: "Your kitten's softness?" %>
    <br>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "button is-info" %>
  </div>
<% end %>

app/views/kittens/_kitten.html.erb
<div id="<%= dom_id kitten %>">
</div>

app/views/kittens/_kittens.erb
<div class="columns">
  <% kittens.each do |kitten| %>
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content row">
            <strong>Name: <%= kitten.name %></strong>
            <small>Age: <%= kitten.age %></small>
            <small>Cuteness: <%= kitten.cuteness %></small>
            <small>Softness: <%= kitten.softness %></small>
            <br>
          </div>
        </div>
      </article>
    </div>
    <p>
      <%= link_to "Show this kitten", kitten %>
    </p>
  <% end %>
</div>

app/views/kittens/edit.html.erb
<h1>Editing kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Show this kitten", @kitten %> |
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="section">
  <div class="container">
    <h1>Kittens</h1>
    <%= render 'kittens', kittens:@kittens %>
    <%= link_to "New kitten", new_kitten_path %>
  </div>
</section>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render "form", kitten: @kitten %>

<br>

<div>
  <%= link_to "Back to kittens", kittens_path %>
</div>

app/views/kittens/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kitten %>

<div>
  <%= link_to "Edit this kitten", edit_kitten_path(@kitten) %> |
  <%= link_to "Back to kittens", kittens_path %>

  <%= button_to "Destroy this kitten", @kitten, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>